name: Release on Merge To Main
on:
  push:
    branches:
      - master
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release version
        id: release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: norelease
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
    outputs:
      sd_version: ${{ steps.release.outputs.version }}
  build:
    if: ${{ needs.versioning.outputs.sd_version }}
    needs: [versioning]
    runs-on: ubuntu-latest
    steps:
      - name: Check release version
        run: echo "I'm running on ${{ needs.versioning.outputs.sd_version }}"
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Node.js Setup
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Cache node_modules directory
        uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install NPM packages
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build frontend
        run: npm run prod
      - name: Cache node_modules mobile directory
        uses: actions/cache@v2
        id: node_module-mobile-cache
        with:
          path: mobile/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install NPM packages
        if: steps.node_module-mobile-cache.outputs.cache-hit != 'true'
        working-directory: mobile
        run: npm install
      - name: Build mobile
        working-directory: mobile
        run: npm run build
      - name: Create an Archive For Release
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r softdesk.zip . -x ".git/*" "node_modules/*" "tests/*" ".github/*" "storage/" package* phpunit.xml "mobile/node_modules/*" # We excluding git, node_modules, and others not needed in production
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: softdesk
          path: softdesk.zip
      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: softdesk.zip
          asset_name: softdesk.zip
          tag: ${{ needs.versioning.outputs.sd_version }}
          overwrite: true
