name: Fix style PSR

on:
  push:
    branches-ignore: [main]
    paths:
      - "app/**.php"
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          php-version: "7.2"
      - name: Report PHP version
        run: php -v
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install —prefer-dist —no-progress —no-suggest
      - name: Run test suite
        run: vendor/bin/phpunit
    # steps:
    #   - uses: actions/checkout@v2
    #     with:
    #       php-version: "7.2"
    #       ref: ${{ github.head_ref }}

    #   - name: Install
    #     run: composer install —prefer-dist —no-progress —no-suggest

    #   - name: Run php-cs-fixer
    #     run: ./vendor/bin/php-cs-fixer fix

    #   - uses: stefanzweifel/git-auto-commit-action@v4
    #     with:
    #       commit_message: Apply php-cs-fixer changes
